### PR TITLE
Implement dropdown for adding transferred contents

### PR DESCRIPTION
**Pull request by ApolloZhu**
## Important

This merges into `mvp` instead of `master`, unless `mvp` has already been merged into `master`

## Changelog

- Shows an auto-updating list of files in any dropdown (currently added to the main dashboard)
- On selecting plain text entries, add the text to the scene at a specified location (current 0, 2, 0)
- The added text can be scaled and moved with controller like other generated objects

## Known Issues

- Can't use the whiteboard feature on the text (consistent with other generated objects)
- Can't rotate the text (consistent with other generated objects)
- Can't generate a display for other file types. This is expected and scheduled to be worked on in the next few weeks.

### CODE REVIEW

**Comment by ApolloZhu** [comment]
I've requested @ebanisadr's review since you'll need to implement displaying images on top of changes introduced in this PR. Let me know if I should alter anything for your needs that you anticipate.

**Comment by ebanisadr** [comment]
A problem I'm having is that generated objects that collide with each other get a velocity, and since they're not affected by gravity they tend to float away; see video.

https://user-images.githubusercontent.com/24218339/153061673-469a76e8-0662-4bba-ac49-d12481ed5b8a.mp4

**Comment by ApolloZhu** [comment]
@ebanisadr that is a problem with the MVP branch, which this PR doesn't change. unity-firebase branch should have the dropdown menu for selecting files and I'm not seeing that in your recording. Can you confirm you are building the correct branch?

**Comment by ApolloZhu** [comment]
@KH-Kyle is it safe to remove the RigidBody from primitive prefabs now? I believe that will fix the floating away issue (and you can commit directly to `MVP` after testing

**Comment by KH-Kyle** [comment]
> @KH-Kyle is it safe to remove the RigidBody from primitive prefabs now? I believe that will fix the floating away issue (and you can commit directly to `MVP` after testing

Yeah. We changed them during yesterday's meeting but it didn't update in the repo. I just update the mvp branch.

**Pull request merged**
